# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'snowflake' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for snowflake
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  target 'snowflakeTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
